from .destinations import destinations_blueprint
from .dashboard import dashboard_blueprint
from .clients import clients_blueprint
from .devices import devices_blueprint
from .parsers import parsers_blueprint
from .general import general_blueprint
from .metrics import metrics_blueprint
from .routes import routes_blueprint
from .topics import topics_blueprint
from .users import users_blueprint
from .mqtt import mqtt_blueprint
from .auth import auth_blueprint